#' detect gait kinematics features
#' @param x data.frame which consists (at least) of columns: joint, plane, curve_id, 0,1,2,...,100
#' @param plane a character vector. Only feature matching this plane will be detected.
#' Whatever is specified here should appear in the \code{fDict} data.frame.
#' For the default feature definitions, the possible choices are \code{"Pel","Hip","Knee","Ankle","FootProgress"}.
#' If \code{NULL} (default) all planes are detected.
#' @param joint a character vector. Only feature matching this joint will be detected. If \code{NULL} (default) all joints are detected.
#' #' Whatever is specified here should appear in the \code{fDict} data.frame.
#' For the default feature definitions, the possible choices are \code{"sag","cor","tra"}.
#' If \code{NULL} (default) all planes are detected.
#' @param comp logical. If \code{TRUE} the return value will have \code{attr(.,"comp")} which gives the clause result of the features.
#' @param fDict a data.frame (at least) with columns \code{fn},\code{joint}, and \code{plane}, used to decide which features to detect.
#' It should have a similiar format to that generated by \link{makeFDict}. If \code{NULL} (default) the default dictionary which comes with the package is used.
#' @return the same as x but augmented with extra columns indicating the detected features.
#' @details For individual feature definitions see \link[=.dtAIR]{definitions}.
#' @examples
#' detectAll(kinematics)
#' detectAll(kinematics, plane="sag")
#'
#' y=detectAll(kinematics, plane="sag", joint="Ankle",comp=T)
#' attr(y,"comp")
#' @export detectAll



## detect All-------------------------------
detectAll=function(x,plane=NULL,joint=NULL,comp=FALSE,fDict=NULL){
  # print("detecting features.")

  # browser()
  if(is.null(fDict))fDict=makeFDict()

  fDict=fDict%>%
    mutate_if(is.factor,as.character)

  suppressMessages({
    if(!is.null(plane))fDict=fDict[fDict$plane%in%plane,]
    if(!is.null(joint))fDict=fDict[fDict$joint%in%joint,]

    fnList=fDict$fn
    detected=vector(mode = "list",length = length(fnList))
    for(i in 1:length(fnList))detected[[i]]=do.call(fnList[i],list(x))


  features=detected%>%
    lapply(function(d)d%>%select(-starts_with("Cl:")))%>%
    Reduce(full_join,.)

  if(is.null(features))return(NULL)

  result=x%>%
    left_join(features,by="curve_id")
  })

  if(comp)attr(result,"comp")=detected

  result

}
